# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Data Visualization
site_url: https://github.com/yy/dviz-course
site_author: YY Ahn
site_description:

# Repository
repo_name: yy/dviz-course
repo_url: https://github.com/yy/dviz-course
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: en
  logo: images/dv.png
  favicon: images/dv.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yyahn/
    - icon: fontawesome/solid/globe
      link: https://yongyeol.com/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - index.md
    - "Module 1: Introduction":
        - m01-intro/class.md
        - m01-intro/lab01.ipynb
    - "Module 2: History":
        - m02-history/class.md
    - "Module 3: Integrity":
        - m03-integrity/class.md
    - "Module 4: Perception":
        - m04-perception/class.md
        - m05-design/class.md
        - m06-data/class.md
        - m07-1D/class.md
        - m08-histogram/class.md
        - m09-estimation/class.md
        - m10-logscale/class.md
        - m11-highdim/class.md
        - m12-maps/class.md
        - m13-text/class.md
        - m14-networks/class.md
    - Labs:
        - m01-intro/lab01.ipynb
        - m01-intro/lab01supp-python_review.ipynb
        - m02-history/lab02.ipynb
        - m03-integrity/lab03.ipynb
        - m04-perception/lab04.ipynb
        - m05-design/lab05.ipynb
        - m06-data/lab06.ipynb
        - m07-1D/lab07.ipynb
        - m08-histogram/lab08.ipynb
        - m09-estimation/lab09.ipynb
        - m10-logscale/lab10.ipynb
        - m11-highdim/lab11.ipynb
        - m12-maps/lab12.ipynb
        - m13-text/lab13.ipynb
        - m14-networks/lab14.ipynb





